export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGIN_START_REFRESH = "LOGIN_START_REFRESH";
export const LOGIN_REFRESH = "LOGIN_REFRESH";
export const LOGOUT = "LOGOUT";
export const PASSWORD_REFRESH = "PASSWORD_REFRESH";
export const PASSWORD_RESET = "PASSWORD_RESET";
export const AUTH_ERROR_CLEAR = "AUTH_ERROR_CLEAR";

export const SNACKBAR_SHOW = "SNACKBAR_SHOW";
export const SNACKBAR_HIDE = "SNACKBAR_HIDE";

export const KIND_PURPOSE_FETCH_ALL = "KIND_PURPOSE_FETCH_ALL";
export const KIND_PURPOSE_FETCH_ONE = "KIND_PURPOSE_FETCH_ONE";
export const KIND_PURPOSE_ADD = "KIND_PURPOSE_ADD";
export const KIND_PURPOSE_UPDATE = "KIND_PURPOSE_UPDATE";
export const KIND_PURPOSE_DELETE = "KIND_PURPOSE_DELETE";
export const KIND_PURPOSE_CHANGE_PAGE = "KIND_PURPOSE_CHANGE_PAGE";
export const KIND_PURPOSE_CHANGE_ROWS_PER_PAGE =
  "KIND_PURPOSE_CHANGE_ROWS_PER_PAGE";
export const KIND_PURPOSE_UNLOAD = "KIND_PURPOSE_UNLOAD";

export const USER_ROLE_FETCH_ALL = "USER_ROLE_FETCH_ALL";
export const USER_ROLE_FETCH_ONE = "USER_ROLE_FETCH_ONE";
export const USER_ROLE_ADD = "USER_ROLE_ADD";
export const USER_ROLE_UPDATE = "USER_ROLE_UPDATE";
export const USER_ROLE_DELETE = "USER_ROLE_DELETE";
export const USER_ROLE_CHANGE_PAGE = "USER_ROLE_CHANGE_PAGE";
export const USER_ROLE_CHANGE_ROWS_PER_PAGE = "USER_ROLE_CHANGE_ROWS_PER_PAGE";
export const USER_ROLE_UNLOAD = "USER_ROLE_UNLOAD";

export const USER_UNLOAD = "USER_UNLOAD";
export const USER_FETCH_ALL = "USER_FETCH_ALL";
export const USER_FETCH_ONE = "USER_FETCH_ONE";
export const USER_ADD = "USER_ADD";
export const USER_UPDATE = "USER_UPDATE";
export const USER_CHANGE_PAGE = "USER_CHANGE_PAGE";
export const USER_CHANGE_ROWS_PER_PAGE = "USER_CHANGE_ROWS_PER_PAGE";

export const USER_SEARCH_CHANGE = "USER_SEARCH_CHANGE";
export const USER_SET_IS_DELETED = "USER_SET_IS_DELETED";

export const TERSTRUCTURE_FETCH_ALL = "TERSTRUCTURE_FETCH_ALL";
export const TERSTRUCTURE_FETCH_ONE = "TERSTRUCTURE_FETCH_ONE";
export const TERSTRUCTURE_ADD = "TERSTRUCTURE_ADD";
export const TERSTRUCTURE_UPDATE = "TERSTRUCTURE_UPDATE";
export const TERSTRUCTURE_DELETE = "TERSTRUCTURE_DELETE";
export const TERSTRUCTURE_UNLOAD = "TERSTRUCTURE_UNLOAD";
